name: Deploy

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        env:
          BASE_URL: "${{ secrets.BASE_URL }}"
          REDIS_PASSWORD: "${{ secrets.REDIS_PASSWORD }}"
          REDIS_HOST: "${{ secrets.REDIS_HOST }}"
      - name: install libraries
        run: yarn install
      - name: install firebase and deploy
        run: npm i firebase-tools -g
      - name: deploy
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN  }}
