name: Deploy to Google

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install libraries
        run: yarn install && yarn run build && cd .output/server && yarn install
      - name: install firebase
        run: npm i firebase-tools -g
      - name: deploy
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN  }}
